import React, { useState } from 'react';
import { 
  Keyboard, 
  Search, 
  Copy, 
  Check, 
  Cpu, 
  CircuitBoard, 
  Cloud, 
  FileText, 
  BookOpen,
  ArrowRight
} from 'lucide-react';
import { ALTIUM_SHORTCUTS } from '../data/shortcuts';
import { CommandShortcut, Tutorial } from '../types';
import { ALL_TUTORIALS } from '../data/catalog';

interface ShortcutsViewProps {
  onSelectTutorial?: (tutorial: Tutorial) => void;
}

export const ShortcutsView: React.FC<ShortcutsViewProps> = ({ onSelectTutorial }) => {
  const [query, setQuery] = useState('');
  const [selectedContext, setSelectedContext] = useState<'All' | 'Schematic' | 'PCB' | 'Develop' | 'General'>('All');
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  const filteredShortcuts = ALTIUM_SHORTCUTS.filter(sc => {
    const matchesContext = selectedContext === 'All' || sc.context === selectedContext || (selectedContext === 'Develop' && sc.context === 'Develop');
    const matchesQuery = sc.key.toLowerCase().includes(query.toLowerCase()) || 
                         sc.action.toLowerCase().includes(query.toLowerCase()) ||
                         sc.context.toLowerCase().includes(query.toLowerCase());
    return matchesContext && matchesQuery;
  });

  const handleCopyKey = (keyStr: string) => {
    navigator.clipboard.writeText(keyStr);
    setCopiedKey(keyStr);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const handleExportMarkdownCheatSheet = () => {
    const text = `# Altium Designer & Altium Develop Hotkey Cheat Sheet
Generated by EET Electronics Product Development Library (learn.eduengteam.com)

## Schematic Shortcuts
${ALTIUM_SHORTCUTS.filter(s => s.context === 'Schematic').map(s => `- **${s.key}**: ${s.action}`).join('\n')}

## PCB Layout Shortcuts
${ALTIUM_SHORTCUTS.filter(s => s.context === 'PCB').map(s => `- **${s.key}**: ${s.action}`).join('\n')}

## General & Develop Workspace Shortcuts
${ALTIUM_SHORTCUTS.filter(s => s.context === 'General' || s.context === 'Develop').map(s => `- **${s.key}**: ${s.action}`).join('\n')}

---
*Independent Educational Resource by Educational Engineering Team (EET)*
`;

    const blob = new Blob([text], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Altium_Hotkey_CheatSheet_${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-8 text-slate-100">
      
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800 pb-6">
        <div className="space-y-2">
          <div className="inline-flex items-center space-x-2 text-xs font-mono bg-blue-950 text-blue-300 border border-blue-800 px-3 py-1 rounded-full">
            <Keyboard className="w-3.5 h-3.5 text-cyan-400" />
            <span>Interactive CAD Hotkey Quick Reference</span>
          </div>
          <h2 className="text-2xl sm:text-4xl font-extrabold text-white tracking-tight">
            Altium Command & Keyboard Shortcuts
          </h2>
          <p className="text-slate-300 text-sm max-w-2xl leading-relaxed">
            Speed up your CAD design workflow. Master sequential command strings (e.g. <code className="bg-slate-900 border border-slate-800 px-1.5 py-0.5 rounded text-cyan-300 font-mono text-xs">P → W</code> for Wire, <code className="bg-slate-900 border border-slate-800 px-1.5 py-0.5 rounded text-cyan-300 font-mono text-xs">Ctrl + W</code> for Interactive Routing).
          </p>
        </div>

        <button
          onClick={handleExportMarkdownCheatSheet}
          className="px-4 py-2.5 bg-slate-900 hover:bg-slate-800 border border-slate-700 text-slate-200 rounded-xl text-xs font-semibold flex items-center space-x-2 shrink-0 transition-colors shadow-md"
        >
          <FileText className="w-4 h-4 text-cyan-400" />
          <span>Export Cheat Sheet (.md)</span>
        </button>
      </div>

      {/* Control Panel: Search & Context Tabs */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 sm:p-6 space-y-4 shadow-xl">
        
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-4">
          
          {/* Search Box */}
          <div className="relative flex-1">
            <Search className="w-4 h-4 absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" />
            <input
              type="text"
              placeholder="Search shortcut key (e.g., 'P -> W', 'DRC', 'Route', 'Layer')..."
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              className="w-full bg-slate-950 border border-slate-700/80 rounded-xl pl-10 pr-4 py-2.5 text-sm text-white placeholder-slate-400 focus:outline-none focus:border-blue-500 transition-all font-mono"
            />
          </div>

          {/* Category Filter Tabs */}
          <div className="flex items-center space-x-1.5 bg-slate-950 p-1 rounded-xl border border-slate-800 shrink-0 text-xs font-medium overflow-x-auto">
            {(['All', 'Schematic', 'PCB', 'Develop', 'General'] as const).map((ctx) => (
              <button
                key={ctx}
                onClick={() => setSelectedContext(ctx)}
                className={`px-3 py-1.5 rounded-lg transition-colors whitespace-nowrap ${
                  selectedContext === ctx 
                    ? 'bg-blue-600 text-white shadow-md' 
                    : 'text-slate-400 hover:text-white'
                }`}
              >
                {ctx}
              </button>
            ))}
          </div>

        </div>

        <div className="text-xs text-slate-400 font-mono">
          Showing <span className="text-white font-bold">{filteredShortcuts.length}</span> keyboard command sequences
        </div>

      </div>

      {/* Shortcuts Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {filteredShortcuts.map((sc, idx) => {
          const isCopied = copiedKey === sc.key;
          
          // Find matching tutorial
          const matchingTutorial = ALL_TUTORIALS.find(t => 
            t.commands?.some(c => c.key === sc.key) ||
            t.fullSummary.toLowerCase().includes(sc.action.toLowerCase()) ||
            t.title.toLowerCase().includes(sc.action.toLowerCase())
          );

          return (
            <div 
              key={idx} 
              className="bg-slate-900 border border-slate-800 rounded-xl p-4 space-y-3 hover:border-slate-700 transition-all shadow-md flex flex-col justify-between"
            >
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className={`text-[10px] font-mono px-2 py-0.5 rounded border uppercase ${
                    sc.context === 'Schematic' 
                      ? 'bg-blue-950 text-blue-300 border-blue-800' 
                      : sc.context === 'PCB' 
                      ? 'bg-emerald-950 text-emerald-300 border-emerald-800' 
                      : 'bg-purple-950 text-purple-300 border-purple-800'
                  }`}>
                    {sc.context} Context
                  </span>

                  <button
                    onClick={() => handleCopyKey(sc.key)}
                    className="p-1.5 hover:bg-slate-800 rounded-lg text-slate-400 hover:text-white transition-colors"
                    title="Copy shortcut key"
                  >
                    {isCopied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  </button>
                </div>

                <div className="flex items-center justify-between pt-1">
                  <code className="text-base font-extrabold text-cyan-300 font-mono bg-slate-950 border border-slate-800 px-2.5 py-1 rounded-lg">
                    {sc.key}
                  </code>
                </div>

                <p className="text-xs text-slate-200 font-medium">
                  {sc.action}
                </p>
              </div>

              {matchingTutorial && onSelectTutorial && (
                <div className="pt-2 border-t border-slate-800/80 flex items-center justify-between text-[11px] text-slate-400">
                  <span className="truncate max-w-[180px]">In: {matchingTutorial.title}</span>
                  <button
                    onClick={() => onSelectTutorial(matchingTutorial)}
                    className="text-blue-400 hover:underline flex items-center space-x-1 shrink-0 font-mono text-[10px]"
                  >
                    <span>Watch Lesson</span>
                    <ArrowRight className="w-3 h-3" />
                  </button>
                </div>
              )}
            </div>
          );
        })}
      </div>

    </div>
  );
};
